#theme: jekyll-theme-cayman
#theme: jekyll-theme-midnight
#theme: jekyll-theme-slate
theme: jekyll-theme-minimal

title: "@もちもち"
description: "競技プログラミングやCTFをしている高2"
logo: img/motimotipurinn.png

twitter:
  username: motimoti_purinn
